name: "Install Claude Code & Plugins"
description: "Extracts Claude Code CLI and plugins from pre-built Docker image (fast, cached)"

inputs:
  image:
    description: "Claude runner Docker image to pull"
    required: false
    default: "ghcr.io/russianoracle-dev/claude-runner:latest"

outputs:
  claude_path:
    description: "Path to installed Claude executable"
    value: ${{ steps.extract.outputs.claude_path }}

runs:
  using: composite
  steps:
    - name: "ðŸ³ Pull claude-runner image"
      id: pull
      shell: bash
      run: |
        IMAGE="${{ inputs.image }}"
        echo "Pulling image: $IMAGE"
        docker pull "$IMAGE"
        echo "âœ… Image pulled"

    - name: "ðŸ“¦ Extract claude binary and plugins"
      id: extract
      shell: bash
      run: |
        IMAGE="${{ inputs.image }}"

        # Diagnostics
        echo "Runner arch: $(uname -m)"
        echo "Image platform:"
        docker image inspect "$IMAGE" --format '{{.Architecture}}/{{.Os}}' 2>/dev/null || true

        # Create a temporary container (not started) to copy files out
        CONTAINER_ID=$(docker create "$IMAGE")

        # Unique path per run to avoid stale file conflicts
        CLAUDE_BIN="/tmp/claude-runner-${GITHUB_RUN_ID}"

        # Check if /root/.local/bin/claude is a symlink inside the container
        REAL_PATH=$(docker run --rm "$IMAGE" sh -c 'readlink -f /root/.local/bin/claude' 2>/dev/null || echo "/root/.local/bin/claude")
        echo "Claude binary real path in image: $REAL_PATH"

        # Extract real binary content (follows symlinks via docker run + cat)
        docker run --rm "$IMAGE" cat "$REAL_PATH" > "$CLAUDE_BIN"
        chmod +x "$CLAUDE_BIN"

        # Diagnostics: show what we extracted
        echo "Binary size: $(wc -c < "$CLAUDE_BIN") bytes"
        echo "Binary type: $(file "$CLAUDE_BIN" 2>/dev/null || head -c 4 "$CLAUDE_BIN" | xxd || true)"

        # Extract plugins directory
        mkdir -p "$HOME/.claude"
        docker cp "$CONTAINER_ID:/root/.claude/plugins" - \
          | tar -xC "$HOME/.claude" 2>/dev/null \
          && echo "âœ… Plugins extracted" \
          || echo "âš ï¸ No plugins dir in image, skipping"

        # Remove the temporary container
        docker rm "$CONTAINER_ID"

        # Verify binary works
        "$CLAUDE_BIN" --version

        echo "claude_path=$CLAUDE_BIN" >> "$GITHUB_OUTPUT"
        echo "âœ… Ready at $CLAUDE_BIN"
